GET http://localhost:5000/products

######
GET http://localhost:5000/products/aaab4e78-8870-441b-bdf4-b7b10946372f

####
POST http://localhost:5000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjliYjBiNjUwLWNiMTMtNGRkYi1iZmEwLWI1YzhkOTViMWYyYyIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImJlbmlAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY3MzE2MjE3LCJleHAiOjE2NjczMTY1MTd9.PoC8rZWD5MYdG-YhhwSU8wHvEjQMvoaBgRKEnB0CfaE
Content-Type: application/json

{
    "name":"Book",
    "price":123
}

######
PATCH  http://localhost:5000/products/aaab4e78-8870-441b-bdf4-b7b10946372f
Content-Type: application/json

{
    "name":"Book Updated",
    "price":123
}

#######
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjliYjBiNjUwLWNiMTMtNGRkYi1iZmEwLWI1YzhkOTViMWYyYyIsInVzZXJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImJlbmlAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY3MzIwMTE4LCJleHAiOjE2NjczMjA0MTh9.9JlexXwH2Iljp8ImS0OlF70Z_XdYsR_0Yiv1yg-XykQ

######
GET http://localhost:5000/users/

####
POST http://localhost:5000/users
Content-Type: application/json

{
    "username":"admin",
    "password": "a",
    "email": "beni@gmail.com",
    "role": "admin"
}

#####
POST http://localhost:5000/login
Content-Type: application/json

{
    "username":"admin",
    "password": "a"
}

######
GET http://localhost:5000/token

######
GET http://localhost:5000/me

######
DELETE  http://localhost:5000/logout